### ISSUE TITLE
having trouble in use PyQt5.QtWebChannel

### ISSUE THREAD

**Issue by alatriste-lee** [baoboa/pyqt5#11]
I'm having trouble using PyQt5.QtWebChannel.

Every time I try to communicate with JavaScript using qtwebchannel, there is big problem. I looked someplace for the sample，even official website link to c++ code like this: [`](http://pyqt.sourceforge.net/Docs/PyQt5/search.html?q=QWebChannelAbstractTransport&check_keywords=yes&area=default) .

Just lookin for a sample of how to use PyQt5.QtWebChannel like in c++ `:    // setup the QWebSocketServer
    QWebSocketServer server(QStringLiteral("QWebChannel Standalone Example Server"), QWebSocketServer::NonSecureMode);
    if (!server.listen(QHostAddress::LocalHost, 12345)) {
        qFatal("Failed to open web socket server.");
        return 1;
    }

    // wrap WebSocket clients in QWebChannelAbstractTransport objects
    WebSocketClientWrapper clientWrapper(&server);

    // setup the channel
    QWebChannel channel;
    QObject::connect(&clientWrapper, &WebSocketClientWrapper::clientConnected,
                     &channel, &QWebChannel::connectTo);

    // setup the dialog and publish it to the QWebChannel
    Dialog dialog;
    channel.registerObject(QStringLiteral("dialog"), &dialog);`

I was wondering if you could help. Please and thank you.

**Comment by baoboa** [comment]
i'm not the author of pyqt and i don't know this specific problem, ask the mailing list for support 

https://www.riverbankcomputing.com/mailman/listinfo/pyqt/
