### ISSUE TITLE
Where can I find the python Documentation for pyqt5

### ISSUE THREAD

**Issue by rodrigch18** [baoboa/pyqt5#12]
I am trying to develop a web browser using pyqt5 but I can't seem to find the pyqt5 api for python. I can only find the c++ api. A lot of the modules don't work the same as pyqt4 like QWebPage.

**Comment by baoboa** [comment]
did you look at this ?
http://pyqt.sourceforge.net/Docs/PyQt5/

**Comment by rodrigch18** [comment]
The modules have no documentation for Python though. For example, http://pyqt.sourceforge.net/Docs/PyQt5/api/qwebengineview.html

**Comment by baoboa** [comment]
python class is wrapped over the c++ one, a pity the documentation is missing, maybe you can request it at the mailing list , i can't help you further than that.

**Comment by Dadaism046** [comment]
我是直接看官方的examples里面的范本。
但也不会是最新的，5.7里都是QWebEngineView，老版本的还是QWebView。
