### ISSUE TITLE
Reason: image not found

### ISSUE THREAD

**Issue by stmtk1** [baoboa/pyqt5#15]
anyone know why this error keeps happening?

ImportError: dlopen(/usr/local/lib/python2.7/site-packages/PySide/QtCore.so, 2): Library not loaded: @rpath/libpyside-python2.7.1.2.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/PySide/QtCore.so
  Reason: image not found

**Comment by baoboa** [comment]
you are using pyside and not pyqt5

**Comment by stmtk1** [comment]
yeah. I'm using pyside.
