### ISSUE TITLE
pyrcc: the -name argument does not do anything

### ISSUE THREAD

**Issue by madebr** [baoboa/pyqt5#18]
The `mInitName` member of `RCCFileInfo` in [pyqt5/pyrcc/rcc.cpp](https://github.com/baoboa/pyqt5/blob/d9f32341e81ff3c29269c738cdfc1ba8b73db1f3/pyrcc/rcc.cpp) and [pyqt5/pyrcc/rcc.hpp](https://github.com/baoboa/pyqt5/blob/d9f32341e81ff3c29269c738cdfc1ba8b73db1f3/pyrcc/rcc.h#L80-L81) is not used anywhere.

That makes it impossible in Python to import a rc module without registering it immediately.

**Comment by baoboa** [comment]
if you find a bug please contact the mailing list 
https://www.riverbankcomputing.com/mailman/listinfo/pyqt/

thanks
