### ISSUE TITLE
Outdated Whitepaper

### ISSUE THREAD

**Issue by ShalokShalom** [baoboa/pyqt5#19]
This use still PyQt4: https://www.riverbankcomputing.com/software/pyqt/whitepaper/index.html

**Comment by baoboa** [comment]
what is the link with this source code ?

**Comment by ShalokShalom** [comment]
That is no source code.

**Comment by baoboa** [comment]
if you open an issue, it should be related to the code of this project, if you complain about the documentation contact the mailing list for that, i'm not responsible for it.

**Comment by ShalokShalom** [comment]
Yeah, i see
