### ISSUE TITLE
webkit examples - QtWebKit deprecated

### ISSUE THREAD

**Issue by umbe1987** [baoboa/pyqt5#21]
Hi,

just tried to use one of the examples ("\webkit\previewer\ui_previewer.py").
I receive an import error "WtWebKitWidgets".
Apparently, it has been superceeded by PyQt5.QtWebEngineWidgets ([reference](https://stackoverflow.com/a/37877273/1979665)).

**Comment by baoboa** [comment]
yes, i hope they fix it in the next version, better comment on that in the mailing list, maybe a dev will see it.

**Comment by baoboa** [comment]
yes, i hope they fix it in the next version, better comment on that in the mailing list, maybe a dev will see it.
