### ISSUE TITLE
No module named ....

### ISSUE THREAD

**Issue by karimnorouzi** [baoboa/pyqt5#26]
I get this error when trying to run your examples. 
could you please let me know what is wrong here ?

c:\WinPython\python-3.4.4.amd64\python hellogl.py
Traceback (most recent call last):
  File "hellogl.py", line 71, in exposeEvent
    self.renderNow()
  File "hellogl.py", line 51, in renderNow
    self.m_gl = self.m_context.versionFunctions()
ImportError: No module named 'PyQt5._QOpenGLFunctions_3_1'

**Comment by baoboa** [comment]
which version of pyQt are you using ? which OS ? 
opengl on windows ? did you install some drivers for that ?
better to ask the mailing list, i never tested pyqt under windows.
