### ISSUE TITLE
Undesired Keyerror

### ISSUE THREAD

**Issue by MatthijsBurgh** [baoboa/pyqt5#31]
https://github.com/baoboa/pyqt5/blob/master/pyuic/uic/properties.py#L406

```
try:
    stdset = bool(int(prop.attrib['stdset']))
except KeyError:
    stdset = True
```
When stdset is not an attribute, it will always raise a KeyError. Which is undesired. While the desired behaviour seems to be that stdset should be set to False. Next to it stdset will be True, if stdset is not an attribute. This seems very unlogical.

Possible solution:
```stdset = 'stdset' in prop.attrib```

**Comment by baoboa** [comment]
i did push the last version of pyqt5 (5.10), i see no change in the source at this level.
You can comment on the mailing list if the code seems illogical to you, my repo is just a mirror of the released source code.
