### ISSUE TITLE
Look'n'feel looks weird on 5.10 and 5.10.1 with pyinstaller

### ISSUE THREAD

**Issue by thekyz** [baoboa/pyqt5#39]
I am compiling a very basic pyqt program with pyinstaller and having no issue with pyqt5 5.9.3 but if I switch to 5.10 or 5.10.1 suddenly the look'n'feel of the compiled application is very wrong.

This image shows the app running with pyqt5 5.9.3 (it looks exactly the same native or with pyinstaller; and it also looks the same native on pyqt5 5.10.x):
<img width="397" alt="screen shot 2018-04-06 at 15 22 26" src="https://user-images.githubusercontent.com/118808/38423503-66d30116-39ae-11e8-8bd5-c7a5fc2d1554.png">

... and this is the same app running with pyinstaller on 5.10.1:
<img width="329" alt="screen shot 2018-04-06 at 15 24 16" src="https://user-images.githubusercontent.com/118808/38423575-9b99a526-39ae-11e8-9d79-d1a4b03698bd.png">

Those screenshots were taken on macosx high sierra but the same behaviour was seen on windows 10.

**Comment by baoboa** [comment]
Yes look strange, i have no idea.
Better to ask the mailing list, this repo is mainly a mirror.
