### ISSUE TITLE
hellogl.py sample: probable typo

### ISSUE THREAD

**Issue by fraca7** [baoboa/pyqt5#46]
Hello. I think that the line

gl.glOrtho(-0.5, +0.5, +0.5, -0.5, 4.0, 15.0)

in hellogl.py (and maybe other samples) should read

gl.glOrtho(-0.5, +0.5, -0.5, +0.5, 4.0, 15.0)

(ie opposite bottom and top). I realized this after copy/pasting the initialization code in my own program. The depth buffer fails in funny ways unless this fix is applied. OpenGL beginner here though, maybe I'm wrong.

**Comment by baoboa** [comment]
Quite possible , hope it will be corrected in the next version.
