### ISSUE TITLE
Can I embedding other function of matplotlib in PyQt5

### ISSUE THREAD

**Issue by DeZhao-Zhang** [baoboa/pyqt5#48]
I find it is easy to embedding matplotlib plot on PyQt GUI , but can i embedding matplotlib.pyplot.imshow in it, so that I can make the numpy array show to a image easily？Hope reply, thanks very much

**Comment by baoboa** [comment]
there is this example 
[link](https://matplotlib.org/gallery/user_interfaces/embedding_in_qt_sgskip.html)
for your question i would say it's more related to matplotlib internals, try their mailing list.
