### ISSUE TITLE
It's this the source code of PyQt5?

### ISSUE THREAD

**Issue by oneTaken** [baoboa/pyqt5#50]
I'm confusing.

**Comment by baoboa** [comment]
it's a mirror of the source code provided by  http://www.riverbankcomputing.com which doesn't provide a git repo , check their website for more info

**Comment by eyllanesc** [comment]
@baoboa  Is this an official mirror of PyQt5?

**Comment by baoboa** [comment]
as said in the readme it's just a personal mirror, feel free to use it

**Comment by eyllanesc** [comment]
@baoboa  Okay, I see that you have updated your README :smile:
