### ISSUE TITLE
examples\painting\svgviewer error in source code

### ISSUE THREAD

**Issue by jernejp21** [baoboa/pyqt5#56]
Under ```def wheelEvent(self, event):```, code ```event.delta()``` pops up error message:

> File "svgviewer.py", line 281, in wheelEvent
>factor = pow(1.2, event.delta() / 240.0)
> AttributeError: 'QWheelEvent' object has no attribute 'delta'

The correct code is ```event.angleDelta().y()```

**Comment by baoboa** [comment]
for help check the mailing list 
 https://www.riverbankcomputing.com/mailman/listinfo/pyqt/
