### ISSUE TITLE
i would like to use qwebengineview for web development  and bind inspector  to current tab,but when i  operate on inspector  the main gui  will crash.Thanks for considering this.

### ISSUE THREAD

**Issue by xiaoyanwa** [baoboa/pyqt5#57]
def test(self):
        self.splitter = QSplitter(Qt.Vertical)
        self.webview=QWebEngineView(self)
        self.webview.load(QUrl("http://www.baidu.com"))
        self.dev_webview = QWebEngineView(self)
        self.splitter.addWidget(self.webview)
        self.splitter.addWidget(self.dev_webview)
        self.dev_webview.page().setInspectedPage(self.webview.page())
        self.splitter.setSizes([100,40])
        self.setCentralWidget(self.splitter)
        self.show()

**Comment by baoboa** [comment]
for help check the mailing list 
 https://www.riverbankcomputing.com/mailman/listinfo/pyqt/
