### ISSUE TITLE
missing variable pyqt5/examples/itemviews/frozencolumn/

### ISSUE THREAD

**Issue by Elan427** [baoboa/pyqt5#62]
Hi, Thanks for the great library translations.
There is a missing variable in frozencolumn.py  pyqt5/examples/itemviews/frozencolumn/
if you resize horizontal columns, it will spit out with an error. Just add the 
self.logicalIndex = 0

I have a question too:
How can i increase number of frozencolumns?
Thanks.

**Comment by baoboa** [comment]
for help check the mailing list 
 https://www.riverbankcomputing.com/mailman/listinfo/pyqt/
