### ISSUE TITLE
 SetStyleSheet a QMenu in QSystemTrayIcon does not work

### ISSUE THREAD

**Issue by algorys** [baoboa/pyqt5#9]
Hello,

I'm using PyQt5 to make an application with `QSystemTrayIcon`. Insise I've added a menu and I try to set style sheet but it does not work.

Here is a part of my code:

``` python
class AppIcon(QSystemTrayIcon):

    def __init__(self, icon, parent=None):
        QSystemTrayIcon.__init__(self, icon, parent)       
        self.menu = QMenu(parent)
        self.menu.setStyleSheet("background-color: blue")
        (...adding some QActions to menu...)
        self.setContextMenu(self.menu)
```

If I make `self.menu.show`, it show the menu with blue background but outside of `QSystemTrayIcon`. And I want to modify the menu inside the QSystemTrayIcon menu.

Is there a way to do that ?

PS : I'm under Ubuntu and install PyQt5 by pip, so not sure it's the best place to ask that ?

**Comment by baoboa** [comment]
this repo is independant from pip

contact  -> Package Index Owner: PhilThompson 

find on the pip page https://pypi.python.org/pypi/PyQt5/5.7

**Comment by algorys** [comment]
Thanks for answer.
